config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # Rutas estaticas
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  get '/reviews', to: 'pages#reviews'
  get '/recycle', to: 'pages#recycle'

  # Rutas con interaccion de BD
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:new, :create, :show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  monetize :total_price_cents

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  belongs_to :user

  monetize :total_price_cents

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :orders, through: :line_items

  belongs_to :category

  monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:pages]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    #if Order.exists?(user_id: current_user)
    # @order = Order.find(user_id: current_user)
    #else
    # @order = Order.new
    #end
    #@line_item = Line_item.new
    @category = Category.find(params[:id])
    @products = Product.where(category_id: @category.id)
  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :price, :image_url)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show]
  #skip_before_action :authenticate_user!, only: [ :show]

  def new
    if params[:product_id]
      @product = Product.find(params[:product_id])
    else
      @product.first
    end
    @order = Order.new
  end

  def create

    @product = Product.find(params[:order][:product_id])
    @order   = Order.new(order_params)
    @order.user = current_user
    if user_signed_in?
      if @order.save!
        LineItem.create!(
          order: @order,
          product: @product,
          amount: 1,
          total_price: @product.price
        )

        @order.update(total_price: @product.price)
        redirect_to @order
      else
        render :new, params: { product_id: @product.id }
      end
    else
      #flash.now[:notice] = 'Message sent!'
      flash.now[:alert] = 'Debe registrarse para completar la orden!'


      render :new, params: { product_id: @product.id }
    end
  end


  def show
    @order = Order.find(params[:id])
  end

  def update
  end

  private

  def order_params
    params.require(:order).permit(:name, :description, :status)
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def contact
  end

  def about
  end

  def reviews
  end

  def recycle
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="bannercategories">
  <div class="container">
     <div class="row">
      <div class="col-sm  m-b-30">
      </div> 
      <div class="col-sm  m-b-30">
      </div>
      <div class="col-sm  m-b-30">
        <h1 class="" align="right">Categoría de Productos</h1>
      </div> 
    </div>     
  </div>
</div>

<div class="categorias container">
  <% Category.all.each do |category| %>
    <div class="targeta1 card bg-dark text-white my-5">
      <%= image_tag category.image_url, class:"card-img rounded" %>
      <div class="card-img-overlay d-flex justify-content-center align-items-center flex-column">
        <%= link_to category.name, category_path(category.id)%> 
        <p class="card-text"><%= category.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="bannerproduct my-5">
    <div class="container border-bottom pb-3">
      <h2 class="" align="center">Detalle del producto</h2>
    </div>
</div>

<div class="container">
  <ul>
    <% @products.each do |product| %>
      
      <div class="row justify-content-center align-items-center">
        <div class="col-6 mb-3">
          <%= image_tag product.image_url, class:"imagenproducto rounded mx-auto d-block" %>
        </div>
        <div class="col-auto m-5">
          <div class="nombreproduct mb-2">
            <%= product.name %>
          </div>
          $<%= product.price %>
          <%= product.price.currency %>
          <%= product.conent %>
          <div class="botones1 mt-3">
            <%= link_to new_order_path(product_id: product.id) do %>
              <div class="compra btn">Comprar</div>
            <% end %>
            <%= link_to categories_path do %>
              <div class="sigue btn ml-2">Añadir a la orden</div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>EquipoVerde</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %> 
    <%= yield %>
    <%= render 'shared/footer' %> 
  </body>
  
</html>

app/views/orders/new.html.erb
<div class="banner20">
   <div class="container d-flex justify-content-center" >
     <div class="center">
        <h1>Tu pedido contribuye a mejorar el planeta</h1>
     </div>
   </div>
</div>
<br>
<br>
<br>
<div class="container">
  <h1>Tu Pedido</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Item</th>
          <th scope="col">Producto</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Subtotal</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
            <% @order.line_items.each do |line_item| %>
            <td><%= line_item.product.name %></td>
            <td><%= line_item.amount %></td>
            <td><%= line_item.total_price %></td>
            <% end %>
          <td></td>
        </tr>
        <tr>
          <th scope="row"> </th>
          <td colspan="2">Total</td>
          <td><%= @order.total_price %></td>
          
        </tr>
      </tbody>
    </table>
     </tr>
      </tbody>
    </table>
</div>
<div class="container mt-4">
  <%= simple_form_for @order do |f| %>
    <%= f.input :status, as: :hidden, input_html: { value: "processed"} %>
    <%= f.input :product_id, as: :hidden, input_html: { value: @product.id } %>
    <div class="btn botoncompletar">
    <%= f.submit "Completar orden", class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h1>Tu orden realizada</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Item</th>
          <th scope="col">Categoría</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Subtotal</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
            <% @order.line_items.each do |line_item| %>
            <td><%= line_item.product.name %></td>
            <td><%= line_item.amount %></td>
            <td><%= line_item.total_price %></td>
            <% end %>
          <td></td>
        </tr>
        <tr>
          <th scope="row"> </th>
          <td colspan="2">Total pagado</td>
          <td><%= @order.total_price %></td>
          
        </tr>
          <!-- <%= link_to categories_path do %>
          <div class="btn btn-info">Seguir comprando</div>
          <% end %>-->

      </tbody>
    </table>

  <%= link_to categories_path do %>
    <div class="btn orden">
      Seguir comprando
    </div>
  <% end %>

</div>

app/views/pages/about.html.erb
<div class="banner3">
   <div class="container d-flex">
     <div class="left">
        <h1>Entregamos productos sustentables<h1>
        <h1>cuidando el medio ambiente. </h1>
     </div>
    <div class="right">
      <div class="text-right d-none d-sm-block d-md">
            <h2><strong> Reciclamos</strong></h2>
            <h4>          Los residuos plasticos pet</h4>
            <h4>          para utilizarlos de materias primas. </strong> </h4>
            <h2><strong> Fabricamos </strong></h2>
            <h4>          Bajo el modelo de economia circular. </h4>
            <h2><strong> Innovamos </strong></h2>
            <h4>          En el diseño y en nuestro procesos de producción. </h4>
      </div> 
    </div>
 </div>
</div>
<div class="card-body">
        <h3 class="card-title-center"><strong>¿Porque elegirnos?</strong></h3>
        <br>
        <br>
        <br>
        <p class="card-subtitle mb-5 text-muted">Actualmente, las empresas dedicadas a dar soluciones a los problemas medioambientales son pocas, pero van en aumento, nosotros queremos ser parte de quienes buscan crear nuevos proyectos que colaboren con la disminución de residuos plásticos que dañan nuestras playas, parques y áreas verdes  con esto en mente quisimos darle un nuevo uso a los residuos que obtuvimos en el proceso de reciclaje y elaboramos productos decorativos para crear espacio únicos en tu hogar.
        Cada producto ha sido creado pensando en un diseño personalizado y único que permita decorar los hogares de quienes nos eligen, al mismo tiempo en que ofrecemos un producto con historia, dándole una segunda oportunidad a los residuos que contaminan el medio ambiente.
        
</p>
        <br>
        <h5 class="card-text"> <em> Ayudanos a descontaminar nuestras areas verdes para crear un mundo mucho mas sustentable y limpio.</em> </h5>
        <br>
  <%= link_to categories_path do %>
    <div class="btn btn-success">
      Volver
    </div>
  <% end %>
</div>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="bannerContact">
    <div class="container-fluid">
      <h2 class="text-center" id="titulo">Contact</h2>
    </div>
    
</div>

<div class="container mt-5 text-center">
  <div class="card-product">

  
  <form method="#" id="formul" action="#">
<! –– <input type="text" name="recipient" value="">
<! –– <input type="hidden" name="subject" value="Asunto del Email">
<! –– <input type="hidden" name="redirect" value="#">
<h2 class="text-center">Consultas:</h2><br />

your name: <br />
<input type="text" name="name" id="nombre"  size="20"><br />
your email:<br />


<input type="text" name="email" id ="correo" size="20"><br />
your message:<br />


<textarea id="mensaje" class="input" name="message" rows="7" cols="30"></textarea><br />


<button onclick="#" id="boton1">enviar</button>

<script>
var nombre1 = document.getElementById('nombre').value;
var correo1 = document.getElementById('correo').value;
var mensaje1 = document.getElementById('mensaje').value;

document.getElementById('boton1').onclick = function(){

    alert("El mensaje fue enviado correctamente!");

}
</script>
</form>

      
      <iframe width="560" height="315" src="https://www.chile-labs.cl/util/videos/video_recicla.mp4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      
    
  </div>
</div>
</body>

app/views/pages/home.html.erb
<div class="bannerhome">
    <div class="container-fluid">
      <h2 class="text-center" id="titulo">Diseña Tu Hogar y Contribuye Con el Medio Ambiente</h2>
    </div>
    <div class="text-center">
      <a href="localhost:3000/categories" class="btn btn-success btn-lg mt-5" role="button" data-bs-toggle="button">Productos</a>
    </div>
</div>
<div class="container mt-5">
  <div class="card-product">
    <img src="https://www.cualestuhuella.cl/files/60abdee72bfd0_890x533.jpg" class="img-fluid"/>
    <div class="card-product-infos">
      <h2 class="pb-4">Qué hacemos</h2>
      <p>Somos una empresa dedicada a la elaboración de productos a partir de envases plásticos, transformando tu hogar sin dañar el planeta. 
Actualmente ofrecemos pastelones sustentables con distintos diseños y maceteros decorativos. 
Nuestra meta es potenciar el modelo de economía circular reutilizando el plástico que día a día contamina nuestro planeta.</p>
    </div>
  </div>
</div>

app/views/pages/recycle.html.erb
<div class="banner4" style="background-image: linear-gradient(rgba(0,0,0,0.125),rgba(0,0,0,0.125)), url(https://www.chile-labs.cl/util/heroku-img/Recicla.jpg);">
</div>
<div class="container mb-5 py-4">
 <div class="row justify-content-center">
   <div class="card" style="width: 30rem;">
     <div class="card-body">
       <h5 class="card-title-center">¿Quieres Reciclar?</h5>
       <h6 class="card-subtitle mb-2 text-muted">Ayudanos a recolectar</h6>
       <p class="card-text"id="recycle">Si quieres ayudarnos a recolectar el plástico que necesitamos para crear nuestros productos, acércate a los puntos de reciclaje de la ciudad.</p>
       <a class="btn btn-flat" href="#">Volver</a>
     </div>
   </div>
   <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d52809.482346452045!2d-70.7788905136631!3d-34.18233113551484!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1spuntos%20reciclaje!5e0!3m2!1ses-419!2scl!4v1631108511380!5m2!1ses-419!2scl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
 </div>
</div>

app/views/products/show.html.erb
<div class="">
  <div class="row">
    <div class="col-6">.col-6</div>
    <div class="col-6">.col-6</div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer py-4 mt-5">
  <div class="container pt-5 pb-2"> 
  <div class="row">
      <div class="col-sm  m-b-30">
        <h2 class="pb-2" id="logonombre">Equipo Verde</h2>
        <ul class="list-unstyled>
          <li class="mb-2"><a href="/about">Sobre Nosotros</a></li>
          <li class="mb-2"><a href="/contact">Contacto</a></li>
        </ul>
        <br>        
      </div>

      <div class="iconos col-sm m-b-30">
        <h4 class="pb-3">Conecta</h4>
        <a href="https://m.facebook.com"><i class="fab fa-fw fa-facebook-f fa-2x pr-4"></i></a>
        <a href="https://twitter.com/"><i class="fab fa-fw fa-twitter fa-2x"></i></a>
        <a href="https://instagram.com/"><i class="fab fa-fw fa-instagram fa-2x pl-4"></i></a>
      </div>

       <div class="col-sm  m-b-30">
        <h4 class="pb-2">Información</h4>
        <ul class="list-unstyled">
          <li class="mb-2"><a href="/about">Términos y Condiciones</a></li>
          <li class="mb-2"><a href="/about">Políticas de Cookies</a></li>
        </ul>
      </div>
  </div>
</div>
  <p class="letrabajo small text-muted d-none d-sm-none d-md-block">Copyright © 2021. GrupoVerde Todos los derechos reservados</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "http://localhost:3000", class: "navbar-brand" do %>
    <%= image_tag "https://previews.123rf.com/images/iglira/iglira1712/iglira171200087/91755007-ilustraci%C3%B3n-de-vector-de-s%C3%ADmbolo-de-reciclaje-verde-aislado-sobre-fondo-blanco-signo-de-reciclaje-en.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
            <li class="nav-item active pr-4 btn btn-flat">
          <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active pr-4 btn btn-flat">
          <%= link_to "Products", categories_path,  class: "nav-link" %>
          </li>
          <li class="nav-item active pr-4 btn btn-flat">
          <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item active pr-4 btn btn-flat">
          <%= link_to "Recycle", recycle_path, class: "nav-link" %>
          </li>
          <li class="nav-item active pr-4 btn btn-flat">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://st2.depositphotos.com/3554337/12097/i/950/depositphotos_120976894-stock-photo-green-user-avatar-icon.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
          
        </li>
      <% else %>

        <li class="nav-item   btn btn-flat">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        
      <% end %>
    </ul>
  </div>
</div>